openapi: 3.0.0
info:
  title: FunnyDev API
  version: 1.0.0
  description: API documentation for FunnyDev Dart Frog backend
servers:
  - url: http://localhost:8081
paths:
  /auth/login:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login successful
        '400':
          description: Invalid credentials
  /auth/register:
    post:
      summary: User registration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                full_name:
                  type: string
      responses:
        '200':
          description: Registration successful
        '400':
          description: Registration failed
  /credits:
    post:
      summary: User registration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                full_name:
                  type: string
      responses:
        '200':
          description: Registration successful
        '400':
          description: Registration failed
  /test:
    get:
      summary: JWT test route
      security:
        - bearerAuth: [ ]
      responses:
        '200':
          description: JWT test route success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  user:
                    type: object
        '401':
          description: Unauthorized
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
