name: mm
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.1.0
  conduit_password_hash: ^5.1.5
  postgres: ^3.5.6
  freezed_annotation: ^3.1.0
  json_annotation: ^4.8.0
  injectable: ^2.5.0
  get_it: ^8.0.3
  dart_either: ^2.0.0
  dart_jsonwebtoken: ^3.2.0
  envied: ^1.1.1
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.5.4
  mocktail: ^1.0.3
  test: ^1.25.5
  very_good_analysis: ^5.1.0
  freezed: ^3.1.0
  json_serializable: ^6.5.0
  injectable_generator: ^2.7.0
  envied_generator: ^1.1.1
